require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'tapeke_admin_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'
  # pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  # pod 'GoogleMaps'
  # pod 'GooglePlaces'
  # pod 'Google-Maps-iOS-Utils'
  
  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
#  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
